
version: '1.0'

services:
  db:
    image: postgres:15.0
    container_name: currency_converter_db_container
    restart: always
    environment:
      POSTGRES_DB: currency_converter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P4ssword
    volumes:
      - postgres_data:/var/lib/postg/dataresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d currency_converter_db"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app_network



  redis:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
